<?php

define("_Msg_Language", "Please select your language:");
$msgWelcome = "Hi dear user" . "\n";
$msgWelcome .= "Now, we are currently reviewing your Twitter account , to do this, send a Twitter username like <code>@jack</code> or <code>jack</code>";
define("_Msg_Welcome", $msgWelcome);
define("_Msg_UserNotFound", "User not found in Twitter.");
define("_Msg_Id", "Id");
define("_Msg_Username", "Username:");
define("_Msg_Name", "Name:");
define("_Msg_Bio", "Bio:");
define("_Msg_Location", "Location:");
define("_Msg_Following", "Following:");
define("_Msg_Followers", "Followers:");
define("_Msg_Listed", "Listed:");
define("_Msg_Tweets", "Tweets:");
define("_Msg_Verified", "Verified:");
define("_Msg_Protected", "Protected:");
define("_Msg_AllTweet", "All tweets:");
define("_Msg_ValidUsername", "Please enter a valid username.");
define("_Msg_PrivatePage", "Your page is private, please set public and try again.");
define("_Msg_PleaseWait", "Please wait ...");
define("_Msg_Exists", "exists.");
define("_Msg_IsNoLimit", "is no limit.");
define("_Msg_SearchLimit", "Search limit: ");
define("_Msg_Ghostlimit", "Ghost limit: ");
define("_Msg_Replylimit", "Reply limit: ");
define("_Msg_Yes", "Yes");
define("_Msg_No", "No");
define("_Msg_SignUp", "SignUp");
define("_Msg_Days", "day(s)");
define("_Msg_Hours", "hour(s)");
define("_Msg_Minutes", "Minute(s)");
define("_Msg_Seconds", "Second(s)");
define("_Msg_Ago", "ago");
define("_Msg_Time", "Time");
define("_Msg_Date", "Date");
define("_Msg_Score", "Score");
define("_Msg_Invited", "Invited");
define("_Msg_YourRank", "Your Rank");
define("_Msg_DeMedal", "Developer Medal (🎖)");
define("_Msg_KiMedal", "King Bot Medal (👑)");
define("_Msg_GiMedal", "Great Bot Medal (🏅)");
define("_Msg_StMedal", "1st Bot Medal (🥇)");
define("_Msg_NdMedal", "2nd Bot medal (🥈)");
define("_Msg_RdMedal", "3rd Bot Medal (🥉)");
$msgLinkDetails = "Send this link to your friend and get gift 😉" . "\n";
$msgLinkDetails .= "To view the number of people who SignUp with your link, enter /profile command, your link: 👇";
define("_Msg_LinkDetails", $msgLinkDetails);
$msgUpdateLan = "Language Updated!" . "\n";
$msgUpdateLan .= "Please click";
define("_Msg_PleaseClick", $msgUpdateLan);
define("_Msg_EmptyScore", "Not having enough score!");
$msgHelp = "Welcome to the bot guide :)" . "\n";
$msgHelp .= "Descriptions of each command are listed in front of it, please read carefully and if you have any suggestions, criticisms or questions about how the bot works, contact the bot support." . "\n \n";
$msgHelp .= "/profile command:" . "\n";
$msgHelp .= "Using this command, you can see the details of your account in the bot, including the date of registration, the number of people registered by you and the points for working with the bot, also, using this command, you can change the language of the bot and receive a special invitation link." . "\n \n";
$msgHelp .= "/link command:" . "\n";
$msgHelp .= "Each user receives ♘ 20 logging in, and for each service in the bot, this score is deducted to a certain number of units, when your score is over, you can use this command and receive a special link and send it to your friends for their entry, you will get 10 ♘ per person and upgrade your rank in the bot, enter the /rank command to get acquainted with the robot ranks." . "\n \n";
$msgHelp .= "/about command:" . "\n";
$msgHelp .= "This command displays the link of the bot specifications and you can use this link to view information such as bot life, updates, etc. related to the bot.";
define("_Msg_Help", $msgHelp);
$msgRank = "Robot ratings:" . "\n \n";
$msgRank .= "Developer Medal (🎖) :" . "\n";
$msgRank .= "- Bot developers have this medal" . "\n \n";
$msgRank .= "King Bot Medal (👑) :" . "\n";
$msgRank .= "- Invite more than 8k member 🙎‍♂️" . "\n";
$msgRank .= "- Get 25% of people's purchases" . "\n \n";
$msgRank .= "Great Bot Medal (🏅) :" . "\n";
$msgRank .= "- Invite from 4k to 8k member 🙎‍♂️" . "\n";
$msgRank .= "- Get 20% of people's purchases" . "\n \n";
$msgRank .= "1st Bot Medal (🥇) :" . "\n";
$msgRank .= "- Invite from 2k to 4k member 🙎‍♂️" . "\n";
$msgRank .= "- Get 15% of people's purchases" . "\n \n";
$msgRank .= "2nd Bot medal (🥈) :" . "\n";
$msgRank .= "- Invite from 1k to 2k member 🙎‍♂️" . "\n";
$msgRank .= "- Get 10% of people's purchases" . "\n \n";
$msgRank .= "3rd Bot Medal (🥉) :" . "\n";
$msgRank .= "- Invite from 1 to 1k member 🙎‍♂️" . "\n";
$msgRank .= "- Get 5% of people's purchases" . "\n \n";
define("_Msg_Rank", $msgRank);
define("_Msg_MoreScore", "Enter /link to get more score.");
define("_Msg_Link", "Link: ");
define("_Msg_Favourite", "Favourite(s): ");
define("_Msg_PrivateUser", "Information about this user is private!");
$msgConnectOne = "Hi dear friend 😎" . "\n";
$msgConnectOne .= "Welcome to the menu of connecting the Twitter account to the bot, of course, we do not need an account password to control, so we do not have access to privacy information 👌🏽" . "\n";
$msgConnectOne .= "This connection is only to protect your privacy from other robot users, for example, after connecting, you can determine whether someone other than yourself can check the account information using me or not, and ..." . "\n";
$msgConnectOne .= "Well, to start, copy the \"<b>profile code</b>\" (one click will copy 😉) and then go to my Twitter page using the \"<b>My Direct 📨</b>\" button and send me the code (my direct is open for all 😬)" . "\n \n";
$msgConnectOne .= "- Profile code: ";
define("_Msg_ConnectOne", $msgConnectOne);
$msgConnectTwo = "After sending the code, be sure to wait for 120 seconds and then click the \"<b>I sent the code</b>\" button, after that, I will send you a series of information from your Twitter account, finally answer the question and that's it. just as easily." . "\n";
$msgConnectTwo .= "To see which bots and apps have access to your Twitter account information, you can open the following path through the Twitter app and block their access:" . "\n \n";
$msgConnectTwo .= "<i>Setting and privacy -> Account -> Apps and sessions -> Connected apps -> [Select one] -> Revoke access</i>" . "\n \n";
$msgConnectTwo .= "You can also connect as many Twitter accounts as you want to this Telegram account 🤓" . "\n";
define("_Msg_ConnectTwo", $msgConnectTwo);
define("_Msg_PrivateAccount", "Do you want bot processes on your Twitter to be accessible to everyone?");
$msgCurrectlySendCode = "Did you send the code correctly? 🤔" . "\n";
$msgCurrectlySendCode .= "Maybe you did not wait for a minute? 🤨" . "\n";
$msgCurrectlySendCode .= "⏳ Please wait a minute ... ";
define("_Msg_CurrectlySendCode", $msgCurrectlySendCode);
define("_Msg_PrivateInformation", "Your information is private inside the robot");
define("_Msg_PublicInformation", "Your information is public inside the robot");
$msgHiddenInformation = "Hi dear user 😎" . "\n";
$msgHiddenInformation .= "Account information is hidden by admin!";
define("_Msg_HiddenInformation", $msgHiddenInformation);
define("_Msg_InjectTwitterProfileOne", "Are you sure to disconnect ");
define("_Msg_InjectTwitterProfileTwo", " from this bot?\n<i>if you do that you can't check Shadowban limit and use unFollowFind command!</i>");
define("_Msg_SubmitExitYes", "You have successfully logged out.\nEnter /connect command to connect the new account");
define("_Msg_SubmitExitNo", "Disconnect was canceled!");
define("_Msg_HaveActiveAdmin", "This Twitter username has a active admin, and you don't connect this username to your Telegram username!");
$msgTimePermision = "Please observe the time limit!" . "\n";
$msgTimePermision .= "Waiting time: ";
define("_Msg_TimePermision", $msgTimePermision);
define("_Msg_ConnectTwitterProfile", "Please first connect your Twitter account with /connect command to this bot and then try again!");
define("_Msg_GetDataActiveAdmin", "You may not access this account information as long as the admin is active.");
$msgUnfollowerCondition = "You must meet the following conditions:" . "\n";
$msgUnfollowerCondition .= "- Followings < 5K" . "\n";
$msgUnfollowerCondition .= "- Followers < 5K" . "\n";
define("_Msg_UnfollowerCondition", $msgUnfollowerCondition);
define("_Msg_Age", "Age");
define("_Msg_SelectAccount", "Please select one theme : 👇🏽");
define("_Msg_Ignore", "Ignore");
define("_Msg_RepeatPerson", "This user is already listed!");
define("_Msg_IgnoreMessageOne", "You put");
define("_Msg_IgnoreMessageTwo", "on the white list, enter the following command to remove this account from the list 👇🏽");
define("_Msg_RemoveMessageOne", "You removed");
define("_Msg_RemoveMessageTwo", "from the white list, enter the following command to put this account to the list 👇🏽");
define("_Msg_NoUnfollowered", "No person unfollowed you!");
define("_Msg_NoWhiteList", "Your WhiteList is empty!");
define("_Msg_SelectIgnoredGroup", "Please select one of the groups below of the ignored person!");
define("_Msg_NotHaveVideo", "This tweet does not have a video!");
define("_Msg_MovieQuality", "Please select movie quality:");
define("_Msg_YourVideos", "Your video(s):");
define("_Msg_PublishedIn", "Published in");
define("_Msg_DoNotHaveLowQuality", "This video does not have a low quality version");
define("_Msg_DoNotHaveHighQuality", "This video does not have a high quality version");
define("_Msg_EmptyVideoList", "Your video list is empty");
define("_Msg_Repair", "🛠 This part is being repaired ..");
$msgDeactivate = "Hi dear friend 😉" . "\n";
$msgDeactivate .= "Unfortunately, due to inconsistencies between the service department (#TwitterApi) and the Bot, #Twitter blocked all our access to its server, I hope this problem will be solved soon and we can continue with strength as in the past, If you have any questions or suggestions, you can contact me with the following ID, There is no advertisement in this Bot, If you wish, you can activate the notification of this Bot so that if you reactivate it, the news will reach your hearing and opinion." . "\n \n";
$msgDeactivate .= "Sincerely yours 🌺" . "\n";
$msgDeactivate .= "Mohammad Zarchi (@ZarchiMohammad)" . "\n";
define("_Msg_Deactivate", $msgDeactivate);
define("_Msg_Renew", "Renew");

define("_Btn_Unfollowers", "Unfollower(s)");
define("_Btn_Unfollowing", "Unfollowing(s)");
define("_Btn_Shadowban", "Shadowban Check");
define("_Btn_UnfollowerFind", "UnfollowerFind");
define("_Btn_ChackProfile", "Check Again");
define("_Btn_Languege", "Languege");
define("_Btn_Link", "Invite Link");
define("_Btn_ConnectAccount", "Connect to TwitterBox");
define("_Btn_ExitFromTwitterAccount", "Exit the bot");
define("_Btn_HaveActiveAdmin", "Have Active Admin");
define("_Btn_LowQuality", "Low Quality");
define("_Btn_HighQuality", "High Quality");
